import { useActor } from "@caffeineai/core-infrastructure";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createActor } from "../backend";
import type { Category, FilterState, PlatformLink, Product, ProductInput } from "../types";
import type { Order } from "../backend";
function useBackendActor() { return useActor(createActor); }
export function useProducts(filter: FilterState) { const { actor, isFetching } = useBackendActor(); return useQuery<Product[]>({ queryKey:["products",filter], queryFn:async()=>actor?actor.getProducts({categoryId:filter.categoryId,searchQuery:filter.searchQuery,minPrice:filter.minPrice,maxPrice:filter.maxPrice,sortBy:filter.sortBy}):[], enabled:!!actor&&!isFetching, staleTime:0 }); }
export function useProduct(id: bigint|null) { const {actor,isFetching}=useBackendActor(); return useQuery<Product|null>({queryKey:["product",id?.toString()],queryFn:async()=>actor&&id!==null?actor.getProduct(id):null,enabled:!!actor&&!isFetching&&id!==null,staleTime:60000}); }
export function useRelatedProducts(productId: bigint|null,limit=6) { const {actor,isFetching}=useBackendActor(); return useQuery<Product[]>({queryKey:["related",productId?.toString(),limit],queryFn:async()=>actor&&productId!==null?actor.getRelatedProducts(productId,BigInt(limit)):[],enabled:!!actor&&!isFetching&&productId!==null,staleTime:60000}); }
export function useCategories() { const {actor,isFetching}=useBackendActor(); return useQuery<Category[]>({queryKey:["categories"],queryFn:async()=>actor?actor.getCategories():[],enabled:!!actor&&!isFetching,staleTime:300000}); }
export function useIsAdmin() { const {actor,isFetching}=useBackendActor(); return useQuery<boolean>({queryKey:["isAdmin"],queryFn:async()=>actor?actor.isAdmin():false,enabled:!!actor&&!isFetching,staleTime:0,retry:3,retryDelay:500,refetchOnMount:true}); }
export function useClaimAdmin() { const {actor}=useBackendActor(); const qc=useQueryClient(); return useMutation({mutationFn:async()=>actor?actor.claimAdmin():false,onSuccess:()=>qc.invalidateQueries({queryKey:["isAdmin"]})}); }
export function useActorReady(){const {actor,isFetching}=useBackendActor();return {actorReady:!!actor&&!isFetching,isFetching};}
export function useRecordClick(){const {actor}=useBackendActor();return useMutation({mutationFn:async(id:bigint)=>{if(actor) await actor.recordClick(id);}});}
export function useGetPlatformLinks(productId:bigint|null){const {actor,isFetching}=useBackendActor();return useQuery<PlatformLink[]>({queryKey:["platformLinks",productId?.toString()],queryFn:async()=>actor&&productId!==null?actor.getPlatformLinks(productId):[],enabled:!!actor&&!isFetching&&productId!==null,staleTime:60000});}
export function useRecordPlatformClick(){const {actor}=useBackendActor();const qc=useQueryClient();return useMutation({mutationFn:async({productId,platform}:{productId:bigint;platform:string})=>{if(actor)await actor.recordPlatformClick(productId,platform);},onSuccess:(_,{productId})=>qc.invalidateQueries({queryKey:["platformLinks",productId.toString()]})});}
export function useAddProduct(){const {actor}=useBackendActor();const qc=useQueryClient();return useMutation({mutationFn:async(input:ProductInput)=>{if(!actor)throw new Error("Not connected");return actor.addProduct(input)},onSuccess:async()=>{await qc.invalidateQueries({queryKey:["products"]});await qc.refetchQueries({queryKey:["products"]})}});}
export function useUpdateProduct(){const {actor}=useBackendActor();const qc=useQueryClient();return useMutation({mutationFn:async({id,input}:{id:bigint;input:ProductInput})=>{if(!actor)throw new Error("Not connected");return actor.updateProduct(id,input)},onSuccess:async(_,{id})=>{await qc.invalidateQueries({queryKey:["products"]});await qc.refetchQueries({queryKey:["products"]});qc.invalidateQueries({queryKey:["product",id.toString()]})}});}
export function useDeleteProduct(){const {actor}=useBackendActor();const qc=useQueryClient();return useMutation({mutationFn:async(id:bigint)=>{if(!actor)throw new Error("Not connected");return actor.deleteProduct(id)},onSuccess:async()=>{await qc.invalidateQueries({queryKey:["products"]});await qc.refetchQueries({queryKey:["products"]})}});}
export function useAddCategory(){const {actor}=useBackendActor();const qc=useQueryClient();return useMutation({mutationFn:async({name,slug,iconName}:{name:string;slug:string;iconName:string})=>{if(!actor)throw new Error("Not connected");return actor.addCategory(name,slug,iconName)},onSuccess:()=>qc.invalidateQueries({queryKey:["categories"]})});}
export function useHotDeals(limit:number){const {actor,isFetching}=useBackendActor();return useQuery<Product[]>({queryKey:["hotDeals",limit],queryFn:async()=>actor?actor.getHotDeals(BigInt(limit)):[],enabled:!!actor&&!isFetching,staleTime:60000});}
export function useProductCountByCategory(categoryId:number|null){const {actor,isFetching}=useBackendActor();return useQuery<bigint>({queryKey:["productCountByCategory",categoryId],queryFn:async()=>actor&&categoryId!==null?actor.getProductCountByCategory(BigInt(categoryId)):0n,enabled:!!actor&&!isFetching&&categoryId!==null,staleTime:60000});}
export interface ProductMetadata{title:string;description:string;imageUrl:string;price:number;originalPrice:number;discountPercent:number;detectedPlatform:string;}
type FetchMetadataResult=Array<{Ok:ProductMetadata}|{Err:string}>;type ActorWithFetchMetadata={fetchProductMetadata(url:string):Promise<FetchMetadataResult>};
export function useFetchProductMetadata(){const {actor}=useBackendActor();return useMutation<ProductMetadata,Error,string>({mutationFn:async(url)=>{if(!actor)throw new Error("Not connected");const result=await(actor as unknown as ActorWithFetchMetadata).fetchProductMetadata(url);const first=result[0];if(!first)throw new Error("Empty response from backend");if("Err" in first)throw new Error(first.Err);return first.Ok;}});}
type ActorWithAdminLogin={adminLogin(email:string,password:string):Promise<boolean>};export function useAdminLogin(){const {actor}=useBackendActor();return useMutation({mutationFn:async({email,password}:{email:string;password:string})=>actor?(actor as unknown as ActorWithAdminLogin).adminLogin(email,password):false});}
export function useCreateOrder(){const {actor}=useBackendActor();const qc=useQueryClient();return useMutation({mutationFn:async(input:{customerName:string;phone:string;address:string;pincode:string;paymentMethod:string;items:Array<{productId:bigint;title:string;imageUrl:string;quantity:bigint;sellingPrice:number}>;subtotal:number;shipping:number;total:number})=>{if(!actor)throw new Error("Not connected");return actor.createOrder(input.customerName,input.phone,input.address,input.pincode,input.paymentMethod,input.items,input.subtotal,input.shipping,input.total);},onSuccess:()=>qc.invalidateQueries({queryKey:["orders"]})});}
export function useOrders(){const {actor,isFetching}=useBackendActor();return useQuery<Order[]>({queryKey:["orders"],queryFn:async()=>actor?actor.getOrders():[],enabled:!!actor&&!isFetching,staleTime:0});}
export function useUpdateOrder(){const {actor}=useBackendActor();const qc=useQueryClient();return useMutation({mutationFn:async(input:{orderId:string;orderStatus:string;supplierStatus:string;supplierOrderId:string;trackingNumber:string;paymentStatus:string})=>{if(!actor)throw new Error("Not connected");return actor.updateOrder(input.orderId,input.orderStatus,input.supplierStatus,input.supplierOrderId,input.trackingNumber,input.paymentStatus);},onSuccess:()=>qc.invalidateQueries({queryKey:["orders"]})});}
export function useCustomerOrder(orderId:string,phone:string){const {actor,isFetching}=useBackendActor();return useQuery<Order|null>({queryKey:["customerOrder",orderId,phone],queryFn:async()=>actor?actor.getCustomerOrder(orderId,phone):null,enabled:!!actor&&!isFetching&&!!orderId&&!!phone,staleTime:15000});}
