/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : CategoryId,
  'name' : string,
  'slug' : string,
  'iconName' : string,
}
export type CategoryId = bigint;
export interface PlatformLink {
  'originalPrice' : number,
  'discountPercent' : bigint,
  'platform' : string,
  'clickCount' : bigint,
  'affiliateLink' : string,
  'price' : number,
}
export interface Product {
  'id' : ProductId,
  'categoryId' : CategoryId,
  'title' : string,
  'originalPrice' : number,
  'platformLinks' : Array<PlatformLink>,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'discountPercent' : bigint,
  'updatedAt' : Timestamp,
  'imageUrl' : string,
  'clickCount' : bigint,
  'affiliateSource' : string,
  'affiliateLink' : string,
  'price' : number,
  'isTrending' : boolean,
}
export interface ProductFilter {
  'categoryId' : [] | [CategoryId],
  'sortBy' : string,
  'maxPrice' : [] | [number],
  'minPrice' : [] | [number],
  'searchQuery' : [] | [string],
}
export type ProductId = bigint;
export interface ProductInput {
  'categoryId' : CategoryId,
  'title' : string,
  'originalPrice' : number,
  'platformLinks' : Array<PlatformLink>,
  'tags' : Array<string>,
  'description' : string,
  'discountPercent' : bigint,
  'imageUrl' : string,
  'affiliateSource' : string,
  'affiliateLink' : string,
  'price' : number,
  'isTrending' : boolean,
}
export interface ProductMetadata {
  'title' : string,
  'originalPrice' : number,
  'description' : string,
  'discountPercent' : number,
  'imageUrl' : string,
  'detectedPlatform' : string,
  'price' : number,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addCategory' : ActorMethod<[string, string, string], Category>,
  'addProduct' : ActorMethod<[ProductInput], Product>,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'claimAdmin' : ActorMethod<[], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'fetchProductMetadata' : ActorMethod<
    [string],
    { 'Ok' : ProductMetadata } |
      { 'Err' : string }
  >,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getHotDeals' : ActorMethod<[bigint], Array<Product>>,
  'getPlatformLinks' : ActorMethod<[ProductId], Array<PlatformLink>>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductCountByCategory' : ActorMethod<[CategoryId], bigint>,
  'getProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'getRelatedProducts' : ActorMethod<[ProductId, bigint], Array<Product>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'recordClick' : ActorMethod<[ProductId], undefined>,
  'recordPlatformClick' : ActorMethod<[ProductId, string], undefined>,
  'updateCategory' : ActorMethod<
    [CategoryId, string, string, string],
    [] | [Category]
  >,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], [] | [Product]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];