/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryId = IDL.Nat;
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'iconName' : IDL.Text,
});
export const PlatformLink = IDL.Record({
  'originalPrice' : IDL.Float64,
  'discountPercent' : IDL.Nat,
  'platform' : IDL.Text,
  'clickCount' : IDL.Nat,
  'affiliateLink' : IDL.Text,
  'price' : IDL.Float64,
});
export const ProductInput = IDL.Record({
  'categoryId' : CategoryId,
  'title' : IDL.Text,
  'originalPrice' : IDL.Float64,
  'platformLinks' : IDL.Vec(PlatformLink),
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'affiliateSource' : IDL.Text,
  'affiliateLink' : IDL.Text,
  'price' : IDL.Float64,
  'isTrending' : IDL.Bool,
});
export const ProductId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Product = IDL.Record({
  'id' : ProductId,
  'categoryId' : CategoryId,
  'title' : IDL.Text,
  'originalPrice' : IDL.Float64,
  'platformLinks' : IDL.Vec(PlatformLink),
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'updatedAt' : Timestamp,
  'imageUrl' : IDL.Text,
  'clickCount' : IDL.Nat,
  'affiliateSource' : IDL.Text,
  'affiliateLink' : IDL.Text,
  'price' : IDL.Float64,
  'isTrending' : IDL.Bool,
});
export const ProductMetadata = IDL.Record({
  'title' : IDL.Text,
  'originalPrice' : IDL.Float64,
  'description' : IDL.Text,
  'discountPercent' : IDL.Float64,
  'imageUrl' : IDL.Text,
  'detectedPlatform' : IDL.Text,
  'price' : IDL.Float64,
});
export const ProductFilter = IDL.Record({
  'categoryId' : IDL.Opt(CategoryId),
  'sortBy' : IDL.Text,
  'maxPrice' : IDL.Opt(IDL.Float64),
  'minPrice' : IDL.Opt(IDL.Float64),
  'searchQuery' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Category], []),
  'addProduct' : IDL.Func([ProductInput], [Product], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'claimAdmin' : IDL.Func([], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'fetchProductMetadata' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'Ok' : ProductMetadata, 'Err' : IDL.Text })],
      [],
    ),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getHotDeals' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getPlatformLinks' : IDL.Func(
      [ProductId],
      [IDL.Vec(PlatformLink)],
      ['query'],
    ),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductCountByCategory' : IDL.Func([CategoryId], [IDL.Nat], ['query']),
  'getProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'getRelatedProducts' : IDL.Func(
      [ProductId, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], []),
  'recordClick' : IDL.Func([ProductId], [], []),
  'recordPlatformClick' : IDL.Func([ProductId, IDL.Text], [], []),
  'updateCategory' : IDL.Func(
      [CategoryId, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(Category)],
      [],
    ),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Opt(Product)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryId = IDL.Nat;
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'iconName' : IDL.Text,
  });
  const PlatformLink = IDL.Record({
    'originalPrice' : IDL.Float64,
    'discountPercent' : IDL.Nat,
    'platform' : IDL.Text,
    'clickCount' : IDL.Nat,
    'affiliateLink' : IDL.Text,
    'price' : IDL.Float64,
  });
  const ProductInput = IDL.Record({
    'categoryId' : CategoryId,
    'title' : IDL.Text,
    'originalPrice' : IDL.Float64,
    'platformLinks' : IDL.Vec(PlatformLink),
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'affiliateSource' : IDL.Text,
    'affiliateLink' : IDL.Text,
    'price' : IDL.Float64,
    'isTrending' : IDL.Bool,
  });
  const ProductId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Product = IDL.Record({
    'id' : ProductId,
    'categoryId' : CategoryId,
    'title' : IDL.Text,
    'originalPrice' : IDL.Float64,
    'platformLinks' : IDL.Vec(PlatformLink),
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'updatedAt' : Timestamp,
    'imageUrl' : IDL.Text,
    'clickCount' : IDL.Nat,
    'affiliateSource' : IDL.Text,
    'affiliateLink' : IDL.Text,
    'price' : IDL.Float64,
    'isTrending' : IDL.Bool,
  });
  const ProductMetadata = IDL.Record({
    'title' : IDL.Text,
    'originalPrice' : IDL.Float64,
    'description' : IDL.Text,
    'discountPercent' : IDL.Float64,
    'imageUrl' : IDL.Text,
    'detectedPlatform' : IDL.Text,
    'price' : IDL.Float64,
  });
  const ProductFilter = IDL.Record({
    'categoryId' : IDL.Opt(CategoryId),
    'sortBy' : IDL.Text,
    'maxPrice' : IDL.Opt(IDL.Float64),
    'minPrice' : IDL.Opt(IDL.Float64),
    'searchQuery' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Category], []),
    'addProduct' : IDL.Func([ProductInput], [Product], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'claimAdmin' : IDL.Func([], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'fetchProductMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : ProductMetadata, 'Err' : IDL.Text })],
        [],
      ),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getHotDeals' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
    'getPlatformLinks' : IDL.Func(
        [ProductId],
        [IDL.Vec(PlatformLink)],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductCountByCategory' : IDL.Func([CategoryId], [IDL.Nat], ['query']),
    'getProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'getRelatedProducts' : IDL.Func(
        [ProductId, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], []),
    'recordClick' : IDL.Func([ProductId], [], []),
    'recordPlatformClick' : IDL.Func([ProductId, IDL.Text], [], []),
    'updateCategory' : IDL.Func(
        [CategoryId, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(Category)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, ProductInput],
        [IDL.Opt(Product)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };