/* eslint-disable */
// @ts-nocheck
import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export class ExternalBlob{_blob?:Uint8Array<ArrayBuffer>|null;directURL:string;onProgress?: (percentage:number)=>void;private constructor(directURL:string,blob:Uint8Array<ArrayBuffer>|null){if(blob)this._blob=blob;this.directURL=directURL}static fromURL(url:string){return new ExternalBlob(url,null)}static fromBytes(blob:Uint8Array<ArrayBuffer>){return new ExternalBlob(URL.createObjectURL(new Blob([new Uint8Array(blob)],{type:"application/octet-stream"})),blob)}async getBytes(){if(this._blob)return this._blob;const r=await fetch(this.directURL);this._blob=new Uint8Array(await (await r.blob()).arrayBuffer());return this._blob}getDirectURL(){return this.directURL}withUploadProgress(f:(p:number)=>void){this.onProgress=f;return this}}
export type Timestamp=bigint;export type CategoryId=bigint;export type ProductId=bigint;
export interface Category{id:CategoryId;name:string;slug:string;iconName:string}export interface PlatformLink{originalPrice:number;discountPercent:bigint;platform:string;clickCount:bigint;affiliateLink:string;price:number}export interface ProductInput{categoryId:CategoryId;title:string;originalPrice:number;platformLinks:Array<PlatformLink>;tags:Array<string>;description:string;discountPercent:bigint;imageUrl:string;affiliateSource:string;affiliateLink:string;price:number;isTrending:boolean}export interface ProductMetadata{title:string;originalPrice:number;description:string;discountPercent:number;imageUrl:string;detectedPlatform:string;price:number}export interface OrderItem{productId:ProductId;title:string;imageUrl:string;quantity:bigint;sellingPrice:number}export interface Order{id:string;supplier:string;customerName:string;phone:string;address:string;pincode:string;paymentMethod:string;paymentStatus:string;orderStatus:string;supplierStatus:string;supplierOrderId:string;trackingNumber:string;items:Array<OrderItem>;subtotal:number;shipping:number;total:number;createdAt:bigint;updatedAt:bigint}export interface Product{id:ProductId;categoryId:CategoryId;title:string;originalPrice:number;platformLinks:Array<PlatformLink>;createdAt:Timestamp;tags:Array<string>;description:string;discountPercent:bigint;updatedAt:Timestamp;imageUrl:string;clickCount:bigint;affiliateSource:string;affiliateLink:string;price:number;isTrending:boolean}export interface ProductFilter{categoryId?:CategoryId;sortBy:string;maxPrice?:number;minPrice?:number;searchQuery?:string}
export interface backendInterface{createOrder(...a:any[]):Promise<Order>;getCustomerOrder(a:string,b:string):Promise<Order|null>;getOrder(a:string):Promise<Order|null>;getOrders():Promise<Order[]>;updateOrder(...a:any[]):Promise<Order|null>;[key:string]:any}
export class Backend implements backendInterface{constructor(private actor:ActorSubclass<_SERVICE>,private _uploadFile:(f:ExternalBlob)=>Promise<Uint8Array>,private _downloadFile:(f:Uint8Array)=>Promise<ExternalBlob>,private processError?:(e:unknown)=>never){}private async call(method:string,args:any[]){try{return await (this.actor as any)[method](...args)}catch(e){if(this.processError)this.processError(e);throw e}}async createOrder(...a:any[]){return this.call("createOrder",a)}async getCustomerOrder(a:string,b:string){const v=await this.call("getCustomerOrder",[a,b]);return v.length?v[0]:null}async getOrder(a:string){const v=await this.call("getOrder",[a]);return v.length?v[0]:null}async getOrders(){return this.call("getOrders",[])}async updateOrder(...a:any[]){const v=await this.call("updateOrder",a);return v.length?v[0]:null}async addCategory(...a:any[]){return this.call("addCategory",a)}async addProduct(...a:any[]){return this.call("addProduct",a)}async adminLogin(...a:any[]){return this.call("adminLogin",a)}async claimAdmin(){return this.call("claimAdmin",[])}async deleteProduct(a:any){return this.call("deleteProduct",[a])}async fetchProductMetadata(a:any){return this.call("fetchProductMetadata",[a])}async getCategories(){return this.call("getCategories",[])}async getHotDeals(a:any){return this.call("getHotDeals",[a])}async getPlatformLinks(a:any){return this.call("getPlatformLinks",[a])}async getProduct(a:any){const v=await this.call("getProduct",[a]);return v.length?v[0]:null}async getProductCountByCategory(a:any){return this.call("getProductCountByCategory",[a])}async getProducts(a:any){return this.call("getProducts",[a])}async getRelatedProducts(a:any,b:any){return this.call("getRelatedProducts",[a,b])}async isAdmin(){return this.call("isAdmin",[])}async recordClick(a:any){return this.call("recordClick",[a])}async recordPlatformClick(a:any,b:any){return this.call("recordPlatformClick",[a,b])}async updateCategory(...a:any[]){const v=await this.call("updateCategory",a);return v.length?v[0]:null}async updateProduct(...a:any[]){const v=await this.call("updateProduct",a);return v.length?v[0]:null}}
export interface CreateActorOptions{agent?:Agent;agentOptions?:HttpAgentOptions;actorOptions?:ActorConfig;processError?:(e:unknown)=>never}
export function createActor(canisterId:string,upload:(f:ExternalBlob)=>Promise<Uint8Array>,download:(f:Uint8Array)=>Promise<ExternalBlob>,options:CreateActorOptions={}){const agent=options.agent||HttpAgent.createSync({...options.agentOptions});const actor=Actor.createActor<_SERVICE>(idlFactory,{agent,canisterId,...options.actorOptions});return new Backend(actor,upload,download,options.processError)}
