/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Category {
    id: CategoryId;
    name: string;
    slug: string;
    iconName: string;
}
export interface ProductInput {
    categoryId: CategoryId;
    title: string;
    originalPrice: number;
    platformLinks: Array<PlatformLink>;
    tags: Array<string>;
    description: string;
    discountPercent: bigint;
    imageUrl: string;
    affiliateSource: string;
    affiliateLink: string;
    price: number;
    isTrending: boolean;
}
export type Timestamp = bigint;
export interface PlatformLink {
    originalPrice: number;
    discountPercent: bigint;
    platform: string;
    clickCount: bigint;
    affiliateLink: string;
    price: number;
}
export interface ProductMetadata {
    title: string;
    originalPrice: number;
    description: string;
    discountPercent: number;
    imageUrl: string;
    detectedPlatform: string;
    price: number;
}
export type CategoryId = bigint;
export type ProductId = bigint;
export interface Product {
    id: ProductId;
    categoryId: CategoryId;
    title: string;
    originalPrice: number;
    platformLinks: Array<PlatformLink>;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    discountPercent: bigint;
    updatedAt: Timestamp;
    imageUrl: string;
    clickCount: bigint;
    affiliateSource: string;
    affiliateLink: string;
    price: number;
    isTrending: boolean;
}
export interface ProductFilter {
    categoryId?: CategoryId;
    sortBy: string;
    maxPrice?: number;
    minPrice?: number;
    searchQuery?: string;
}
export interface backendInterface {
    addCategory(name: string, slug: string, iconName: string): Promise<Category>;
    addProduct(input: ProductInput): Promise<Product>;
    adminLogin(email: string, password: string): Promise<boolean>;
    claimAdmin(): Promise<boolean>;
    deleteProduct(id: ProductId): Promise<boolean>;
    fetchProductMetadata(url: string): Promise<{
        __kind__: "Ok";
        Ok: ProductMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    getCategories(): Promise<Array<Category>>;
    getHotDeals(limit: bigint): Promise<Array<Product>>;
    getPlatformLinks(productId: ProductId): Promise<Array<PlatformLink>>;
    getProduct(id: ProductId): Promise<Product | null>;
    getProductCountByCategory(categoryId: CategoryId): Promise<bigint>;
    getProducts(filter: ProductFilter): Promise<Array<Product>>;
    getRelatedProducts(productId: ProductId, limit: bigint): Promise<Array<Product>>;
    isAdmin(): Promise<boolean>;
    recordClick(productId: ProductId): Promise<void>;
    recordPlatformClick(productId: ProductId, platform: string): Promise<void>;
    updateCategory(id: CategoryId, name: string, slug: string, iconName: string): Promise<Category | null>;
    updateProduct(id: ProductId, input: ProductInput): Promise<Product | null>;
}
import type { Category as _Category, CategoryId as _CategoryId, Product as _Product, ProductFilter as _ProductFilter, ProductMetadata as _ProductMetadata } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCategory(arg0: string, arg1: string, arg2: string): Promise<Category> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async addProduct(arg0: ProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0);
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async claimAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdmin();
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async fetchProductMetadata(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: ProductMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchProductMetadata(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchProductMetadata(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getHotDeals(arg0: bigint): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotDeals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotDeals(arg0);
            return result;
        }
    }
    async getPlatformLinks(arg0: ProductId): Promise<Array<PlatformLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformLinks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformLinks(arg0);
            return result;
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductCountByCategory(arg0: CategoryId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductCountByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductCountByCategory(arg0);
            return result;
        }
    }
    async getProducts(arg0: ProductFilter): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts(to_candid_ProductFilter_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts(to_candid_ProductFilter_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getRelatedProducts(arg0: ProductId, arg1: bigint): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelatedProducts(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelatedProducts(arg0, arg1);
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async recordClick(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordClick(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordClick(arg0);
            return result;
        }
    }
    async recordPlatformClick(arg0: ProductId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPlatformClick(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPlatformClick(arg0, arg1);
            return result;
        }
    }
    async updateCategory(arg0: CategoryId, arg1: string, arg2: string, arg3: string): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1, arg2, arg3);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1, arg2, arg3);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: ProductId, arg1: ProductInput): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ok: _ProductMetadata;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ProductMetadata;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function to_candid_ProductFilter_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductFilter): _ProductFilter {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId?: CategoryId;
    sortBy: string;
    maxPrice?: number;
    minPrice?: number;
    searchQuery?: string;
}): {
    categoryId: [] | [_CategoryId];
    sortBy: string;
    maxPrice: [] | [number];
    minPrice: [] | [number];
    searchQuery: [] | [string];
} {
    return {
        categoryId: value.categoryId ? candid_some(value.categoryId) : candid_none(),
        sortBy: value.sortBy,
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none(),
        searchQuery: value.searchQuery ? candid_some(value.searchQuery) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
